######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 24 21:20:04 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += base64.h mailsender.h
SOURCES += base64.cpp mailsender.cpp main.cpp

QT += network
CONFIG += qtestlib